# Generated by Django 4.2.22 on 2025-06-21 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('num_of_guests', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='booking_date',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='guests_num',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='title',
        ),
    ]
