# Generated by Django 4.2.22 on 2025-06-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking_table_delete_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
