# Generated by Django 4.2.22 on 2025-06-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_rename_table_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='price',
            new_name='guestes_num',
        ),
        migrations.AddField(
            model_name='booking',
            name='inventory',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='booking_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
