# Generated by Django 4.2.22 on 2025-06-14 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_name_booking_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='booking_date',
            field=models.DateField(default=datetime.date(2025, 6, 14)),
        ),
    ]
